### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by gui11aume** [ezorita/mapper#11]
When napping this read in the genome of Entrophila eduardi (release 3), the mapper hangs.
CGACAGCGTATTTTTTTTTTTTTTCAAATTGATGGAGGTAGGGTAGACGT

**Comment by ezorita** [comment]
Fails at shrink('T'*14), which is the last suffix of the LCP table (what is the offset/LCP there?).

**Comment by ezorita** [comment]
Fix "BUG" comments at suffix_ssv().
