### ISSUE TITLE
suffix_shrink() and TTTTTTTTTTT

### ISSUE THREAD

**Issue by gui11aume** [ezorita/mapper#12]
In the genome of Entrophila eduardi, a suffix with 12 Ts has range {depth = 12, sp = 337472942, ep = 337473074}. When calling `suffix_shrink()` on it, the result is {depth = 179, sp = 337472942, ep = 337473075}. The depth has increased to 179.

**Comment by ezorita** [comment]
Build the index with the last commit and try again.
